---
title: "Clean Water Act Rule Changes: Impacts to New Mexico"
resource_files:
- basic_count_long.RDS
- nm_census_tracts.RDS
- nm_connected_stream.RDS
- nm_county.RDS
- nm_disconnected_stream.RDS
- nm_npdes.RDS
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<style>
  .datatables{
    overflow:auto;
  }
</style>

```{r setup, include=FALSE, context = "data"}
library(flexdashboard)
library(leaflet)
library(tidyverse)
library(sf)
library(ggrepel)
library(RColorBrewer)
library(DT)

options(scipen = 999)
## following fix is screen and resolution specific. therefore only use as last resort
#options(DT.options = list(scrollY = "600px", scrollX = "300px", pageLength = 100))

# reading all inputs

# nm_counties <- readRDS("nm_county.RDS")
nm_census_tracts <- readRDS("nm_census_tracts.RDS")
nm_disconnected_stream <- readRDS("nm_disconnected_stream.RDS")
nm_connected_stream <- readRDS("nm_connected_stream.RDS")
HDI_indicators <- readRDS("HDI_indicators.RDS")
basic_count <- readRDS("basic_count_long.RDS")
nm_streams_summary_df <- readRDS("nm_streams_summary.RDS")
county_level_weighted <- readRDS("county_level_weighted.RDS")
nm_npdes <- readRDS("nm_npdes.RDS")
total_basic_count <- readRDS("state_total_basic_count.RDS")
nm_census_tracts_df <- readRDS("nm_census_tracts_df.RDS")
nm_surface_water_intake <- readRDS("nm_surface_water_intake.RDS")
nm_pws_merged <- readRDS("nm_pws_merged.RDS")
dwv_index_table <- readRDS("dwv_index_table.RDS")

# joining hdi_indicators to census_tract_shp
nm_census_tracts <- inner_join(nm_census_tracts, HDI_indicators)
 

# other county-level summary statistics weighted by population
fivenum_hdi <- fivenum(county_level_weighted$weighted_HDI)
fivenum_income <- fivenum(county_level_weighted$weighted_income)
fivenum_education <- fivenum(county_level_weighted$weighted_edn)
fivenum_expectancy <- fivenum(county_level_weighted$weighted_expectancy)
fivenum_disconnected <- fivenum(nm_streams_summary_df$length_unprotected)
fivenum_disconnected_pct <- fivenum(nm_streams_summary_df$pct_unprotected)

# color bins
bins <- c(0.5, 0.6, 0.7, 0.8, 0.9)
```

Statewide
==================

Column {data-width=300 .sidebar}
-----------------------------------------------------------------------

### New Mexico

```{r, cache = TRUE}
HTML(paste("In this dashboard, you will find a variety of information on how New Mexico may be affected by changes in the definition of Waters of the United States, under the Clean Water Act. These changes mean that most of New Mexico's streams and rivers will no longer be protected. This dashboard is intended to show socio-economic impacts using the Human Development Index (HDI) and provide Drinking Water Vulnerability Index.", " ", "The HDI is a statistic used by the United Nations to rank countries into tiers of human development. It looks at life expectancy, education, and per capita income. This has been modified for use in New Mexico where each county and census tract is evaluated.", " ", "The Drinking Water Vulnerability Index evaluates the vulnerability of public water systems (PWS). It estimates the degree of exposure of surface water sources and the community's ability to circumvent a potential contamination or negative impact to their drinking water. The index takes into consideration household income, degree of impact to the PWS surface water intakes, and the availability of alternative sources of water. The index is on a scale of 1 to 10, with 10 being the most vulnerable.", sep = "<br/>"))
```

Column {data-width=500 .tabset}
-----------------------------------------------------------------------

### Unprotected Waterways
```{r}
renderLeaflet({
  pal <- colorBin("Blues", domain = nm_census_tracts$HDI, bins = bins)
  vul_pal <- colorBin("Reds", domain = nm_pws_merged$Index, bins = c(2,4,6,8))
  leaflet() %>%
    addProviderTiles(providers$Stamen.Toner, options = providerTileOptions(zIndex = 7)) %>%
    setView(lng = -105.87, lat = 34.52, zoom = 8) %>%
    addPolygons(data = nm_census_tracts, label = ~round(HDI, 3), group = "HDI",
                fillColor = ~pal(HDI), fillOpacity = 0.75, weight = 0, opacity = 0, color = "white") %>%
    addPolygons(data = nm_pws_merged, label = nm_pws_merged$PublicSyst.y, group = "Water System",
                fillColor = ~vul_pal(Index), fillOpacity = 0.75, weight = 0, opacity = 0, color = "white") %>%
    addPolylines(data = st_zm(nm_disconnected_stream), label = ~GNIS_Name, group = "Unprotected Streams",
                 color = "#fb6a4a", weight = 1.2) %>%
    addPolylines(data = st_zm(nm_connected_stream), label = ~GNIS_Name, group = "Protected Streams",
                 color = "#08519c", weight = 1.2) %>%
    addCircleMarkers(data = nm_npdes, label = ~FACILITYNA, group = "Pollutant Sources", 
                     color = "#e41a1c", radius = 6, stroke = F, fillOpacity = 0.5, clusterOptions = markerClusterOptions()) %>%
    addLayersControl(overlayGroups = c("HDI", "Unprotected Streams", "Protected Streams", "Water System", "Pollutant Sources"),
                     options = layersControlOptions(collapsed = FALSE)) %>%
    hideGroup(c("Unprotected Streams", "Protected Streams", "Pollutant Sources", "Water System")) %>%
    addLegend("bottomright", pal = pal, values = nm_census_tracts$HDI, title = "Human Development Index", opacity = 0.7) %>%
    addLegend("bottomleft", pal = vul_pal, values = nm_pws_merged$Index, title = "Vulnerability Index", opacity = 0.7)
   })
```


  
### Vulnerability Plot
```{r}
renderPlot({
  ggplot(nm_pws_merged, aes(x = Population, y = as.numeric(MedianIncome))) + 
    geom_point(aes(color = Index)) +
    scale_color_gradient(low = "#fee0d2", high = "#de2d26") + 
    geom_text_repel(aes(label = PublicSyst.y), size = 4.0) + 
    labs(title = "At-Risk Public Water Systems", subtitle = "Public Water Systems are most vulnerable when median household incomes are low, population sizes are huge, and vulnerability scores high.",
         x = "Population Size", y = "Median Household Income ($)",
         colour = "Vulnerability \nIndex")
   })
``` 
  
### Public Water Systems  
```{r}
renderDataTable({dwv_index_table})
```

  
Column {data-width=200, .no-padding}
-----------------------------------------------------------------------

### Statewide Waterways Status

```{r, cache = TRUE}
nm_protected_stream_length <- nm_streams_summary_df %>%
  mutate(length_protected = ifelse(pct_unprotected == 100, 0, length_unprotected/pct_unprotected*(100-pct_unprotected))) %>%
  ungroup() %>%
  select(length_protected) %>%
  unlist() %>%
  sum()

nm_unprotected_stream_length <- nm_streams_summary_df %>%
  ungroup() %>%
  select(length_unprotected) %>%
  unlist() %>%
  sum()

state_stream_df <- data.frame(
  category = c("Protected", "Unprotected"),
  length = c(nm_protected_stream_length, nm_unprotected_stream_length)) 
state_stream_df$frac <- state_stream_df$length/sum(state_stream_df$length)
state_stream_df$ymax <- cumsum(state_stream_df$frac)
state_stream_df$ymin <- c(0, head(state_stream_df$ymax, n=-1))
state_stream_df$labelPosition <- (state_stream_df$ymax + state_stream_df$ymin)/2
state_stream_df$label <- paste0(state_stream_df$category, ": ", round(100*state_stream_df$frac), "%")

ggplot(state_stream_df, aes(ymax = ymax, ymin = ymin, xmax = 4, xmin = 3, fill = category)) + 
  geom_rect() +
  geom_text(x = 2, aes(y = labelPosition, label = label, color = category), size = 5.5) + 
  scale_fill_manual(values = c("#80b1d3", "#fb8072")) + 
  scale_color_manual(values = c("#80b1d3", "#fb8072")) + 
  coord_polar(theta = "y") + 
  xlim(c(-1, 4)) + 
  theme_void() + 
  theme(legend.position = "none")
```

### Statewide HDI Breakdown

```{r cache = TRUE}
ggplot(HDI_indicators, aes(HDI)) + 
  geom_histogram(binwidth = 0.01) + 
  labs(y = "No. Census Tracts", x = "Human Development Index") + 
  scale_x_continuous(breaks = seq(0.5, 0.9, 0.05)) + 
  theme_classic() + 
  theme(axis.text.x = element_text(face = "bold", size = 11),
        axis.text.y = element_text(face = "bold", size = 11),
        axis.title.x = element_text(face = "bold"),
        axis.title.y = element_text(face = "bold"))
```
  
### Statewide Racial/Ethnic Breakdown  
  
```{r cache = TRUE}
ggplot(total_basic_count, aes(x = Race, y = value)) + 
    geom_point(col = "#fc8d62", size = 5) + 
    geom_segment(aes(x = Race, xend = Race, y = 0, yend = value), col = "#969696", size = 2) +
    scale_x_discrete(labels = c("Asian", "Biracial", "Black", "Hispanic", "Pacific Islander", "Native American", "Other", "White")) + 
    labs(x = "Race", y = "Est. % of State Totals") +
    theme(panel.background = element_rect(fill = "white"), 
          panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
          axis.text.x = element_text(angle = 45, face = "bold", size = 11),
          axis.text.y = element_text(face = "bold", size = 11),
          axis.title.x = element_text(face = "bold"),
          axis.title.y = element_text(face = "bold"))
```

    
County
==================

Column {data-width=200 .sidebar}
-----------------------------------------------------------------------

### New Mexico

```{r}
selectInput("county",
            "County:",
            choices = sort(unique(nm_census_tracts$county)),
            "Bernalillo County")

selectInput("pws", 
            "Water System:",
            choices = sort(nm_pws_merged$PublicSyst.y),
            "ALBUQUERQUE WATER SYSTEM")
```


Column {data-width=600 .tabset}
-----------------------------------------------------------------------
### Unprotected Waterways

```{r}
reactive_county <- reactive({
    nm_census_tracts_filtered <- nm_census_tracts %>%
      filter(county == input$county)
    nm_pws_merged_filtered <- nm_pws_merged %>%
      filter(PublicSyst.y == input$pws)
    pal <- colorBin("Blues", domain = nm_census_tracts_filtered$HDI, bins = bins)
    nm_streams_filtered <- nm_disconnected_stream %>%
      filter(NAMELSAD == input$county)
    nm_connected_streams_filtered <- nm_connected_stream %>%
      filter(NAMELSAD == input$county)
    if(nrow(nm_connected_streams_filtered) > 0){
    leaflet() %>%
      addProviderTiles(providers$Stamen.Toner) %>%
      addPolygons(data = nm_pws_merged_filtered, label = paste(nm_pws_merged_filtered$PublicSyst.y,
                                                               nm_pws_merged_filtered$Index, sep = ": "), 
                  group = "Water System", fillColor = "white", fillOpacity = 0, weight = 1, opacity = 1, color = "black") %>%
      addPolygons(data = nm_census_tracts_filtered, label = ~round(HDI, 3), group = "HDI",
                 fillColor = ~pal(HDI), fillOpacity = 0.5, weight = 0.75, opacity = 1, color = "white") %>%
      addPolylines(data = st_zm(nm_streams_filtered), label = ~GNIS_Name, group = "Unprotected Streams",
                  color = "#fb6a4a", weight = 1.2) %>%
      addPolylines(data = st_zm(nm_connected_streams_filtered), label = ~GNIS_Name, group = "Protected Streams",
                  color = "#08519c", weight = 1.2) %>%
      addLayersControl(overlayGroups = c("HDI", "Water System", "Unprotected Streams", "Protected Streams"),
                       options = layersControlOptions(collapsed = FALSE)) %>%
      hideGroup(c("Unprotected Streams", "Protected Streams")) %>%
      addLegend("bottomright", pal = pal, values = nm_census_tracts_filtered$HDI, title = "HDI", opacity = 0.7)
    }
    else{
    leaflet() %>%
      addProviderTiles(providers$Stamen.Toner) %>%
      addPolygons(data = nm_pws_merged_filtered, label = paste(nm_pws_merged_filtered$PublicSyst.y,
                                                               nm_pws_merged_filtered$Index, sep = ": "), 
                  group = "Water System", fillColor = "white", fillOpacity = 0, weight = 1, opacity = 1, color = "black") %>%
      addPolygons(data = nm_census_tracts_filtered, label = ~round(HDI, 3), group = "HDI",
                 fillColor = ~pal(HDI), fillOpacity = 0.5, weight = 0.75, opacity = 1, color = "white") %>%
      addPolylines(data = st_zm(nm_streams_filtered), label = ~GNIS_Name, group = "Unprotected Streams",
                  color = "#fb6a4a", weight = 1.2) %>%
      addLayersControl(overlayGroups = c("HDI", "Water System", "Unprotected Streams", "Protected Streams"),
                       options = layersControlOptions(collapsed = FALSE)) %>%
      hideGroup(c("Unprotected Streams", "Protected Streams")) %>%
      addLegend("bottomright", pal = pal, values = nm_census_tracts_filtered$HDI, title = "HDI", opacity = 0.7)  
    }
    })
    
    
renderLeaflet({
     reactive_county()
   })
```

### Demographics
```{r}
demographics <- reactive({
  filtered_basic_count <- basic_count %>%
    filter(county == input$county)
  ggplot(filtered_basic_count, aes(x = Race, y = value)) + 
    geom_point(col = "#fc8d62") + 
    geom_segment(aes(x = Race, xend = Race, y = 0, yend = value), col = "#969696") +
    scale_x_discrete(labels = c("Asian", "Biracial", "Black", "Hispanic", "Pacific Islander", "Native American", "Other", "White")) + 
    labs(x = "Race", y = "Est. % of County Totals", title = paste("Population of", input$county, sep = " ")) +
    theme(panel.background = element_rect(fill = "white"), panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    coord_flip()
})
renderPlot({
  demographics()
})
```


### Comparing County with NM

```{r}
disconnected_length <- reactive({
  nm_streams_summary_df %>% 
    ungroup() %>%
    filter(NAMELSAD == input$county) %>% 
    select(length_unprotected) %>% 
    unlist()})

reactive_county_hdi <- reactive({
    county_level_weighted %>% 
    filter(county == input$county) %>% 
    select(weighted_HDI) %>% 
    unlist()})

county_life_exp <- reactive({
  county_level_weighted %>% 
    filter(county == input$county) %>% 
    select(weighted_expectancy) %>% 
    unlist()})

education_yrs <- reactive({
  county_level_weighted %>% 
    filter(county == input$county) %>% 
    select(weighted_edn) %>% 
    unlist()})

income_pc <- reactive({
  county_level_weighted %>% 
    filter(county == input$county) %>% 
    select(weighted_income) %>% 
    unlist()})

comparison_plot_df_plot <- reactive({
  metric <- c("HDI", "Unprotected Waterways", "Life Expectancy", "Years of Education", "Income")
  disconnected_val <- round(100*disconnected_length()/fivenum_disconnected[3])-100
  hdi_val <- round(100*reactive_county_hdi()/fivenum_hdi[3])-100
  life_exp_val <- round(100*county_life_exp()/fivenum_expectancy[3])-100
  education_val <- round(100*education_yrs()/fivenum_education[3])-100
  income_val <- round(100*income_pc()/fivenum_income[3])-100
  values <- c(hdi_val, disconnected_val, life_exp_val, education_val, income_val)
  comparison_df <- cbind(metric, values) %>%
    as.data.frame()
  comparison_df <- comparison_df[order(comparison_df$values),]
  comparison_df$metric <- factor(comparison_df$metric, levels = comparison_df$metric)
  ggplot(comparison_df, aes(x = metric, y = as.numeric(values), label = values)) +
    geom_bar(stat = "identity", width = 0.5) + 
    labs(title = paste("Comparing", input$county, "Against NM Median", sep = " "),
         y = "% (Below [-ve] / Above [+ve]) State Median",
         x = "Metric") + 
    coord_flip()
})

renderPlot({
  comparison_plot_df_plot()
})
```


Column {data-width=200}
-----------------------------------------------------------------------
### Unprotected Waterways

```{r}
renderValueBox({
  valueBox(disconnected_length(),
           caption = "Unprotected Waterways (mi)",
           icon = 'fa-tint-slash',
           color = ifelse(disconnected_length() < fivenum_disconnected[3], "primary", 
                          ifelse(disconnected_length() > fivenum_disconnected[4], "danger", "warning")))})
```

### Unprotected Waterways_pct

```{r}
disconnected_pct <- reactive({
  nm_streams_summary_df %>% 
    ungroup() %>%
    filter(NAMELSAD == input$county) %>% 
    select(pct_unprotected) %>% 
    unlist()})

renderValueBox({
  valueBox(disconnected_pct(),
           caption = "Unprotected Waterways (% of Total)",
           icon = 'fa-tint-slash',
           color = ifelse(disconnected_pct() < fivenum_disconnected_pct[3], "primary", 
                          ifelse(disconnected_pct() > fivenum_disconnected_pct[4], "danger", "warning")))})
```

### County HDI

```{r}
renderValueBox({
  valueBox(reactive_county_hdi(),
           caption = "HDI",
           icon = 'fa-user',
           color = ifelse(reactive_county_hdi() > fivenum_hdi[3], "primary", 
                          ifelse(reactive_county_hdi() < fivenum_hdi[2], "danger", "warning"))
           )}
  )
```

### Mean Life Expectancy

```{r}
renderValueBox({
  valueBox(county_life_exp(),
           caption = "Life Expectancy",
           icon = 'fa-heartbeat',
           color = ifelse(county_life_exp() > fivenum_expectancy[3], "primary", 
                          ifelse(county_life_exp() < fivenum_expectancy[2], "danger", "warning")))})
```

### Mean Years of Schooling

```{r}
renderValueBox({
  valueBox(education_yrs(),
           caption = "Years of Education for Adults",
           icon = 'fa-book',
           color = ifelse(education_yrs() > fivenum_education[3], "primary", 
                          ifelse(education_yrs() < fivenum_education[2], "danger", "warning")))})
```

### Mean Annual Income

```{r}
renderValueBox({
  valueBox(income_pc(),
           caption = "Income per Capita ($)",
           icon = 'fa-dollar-sign',
           color = ifelse(income_pc() > fivenum_income[3], "primary", 
                          ifelse(income_pc() < fivenum_income[2], "danger", "warning")))})
```
